import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/core-components/MuiNextLink';
import { Container, Grid, Stack } from '@mui/material';
//import GetStarted from '@components/GetStarted';
import MintNFT from '@components/web3/mint-nft';
import Image from 'next/image';

//THE TOP OF THE PAGE BELOW HEADER
export default function Home() {
  return (
    <Container>
      <Head>
        <title>TDA NFT Minting</title>
        <meta name="description" content="Generated by create next app" />
              
      </Head>

      <main className={styles.main}>



           <h1 className={styles.title}>
                  Top Dog Release       
           </h1>

           <p>
                  <h2 className={styles.subtitle}>DOG LAYER NFT PRESALE</h2>
           </p>


           <hr style={{ height: 4, width: "75%" }} />

        

        {/*<GetStarted />*/}

          <MintNFT />

       

      </main>
    </Container>
  )
}
