import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/core-components/MuiNextLink';
import { Container, Stack } from '@mui/material';
import GetStarted from '@components/GetStarted';
import MintNFT from '@components/web3/mint-nft';

//THE TOP OF THE PAGE BELOW HEADER
export default function Home() {
  return (
    <Container>
      <Head id="home">
        <title>web3-react with nft merkle tree minting scaffold</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Top Dog Affiliation
        </h1>

        <p className={styles.description}>
          <Stack spacing={1}>
            <p>
              The dogs you'll remember
            </p>
            <p>
            Created by <code className={styles.code}><a href="https://twitter.com/straightup" target="_blank" rel="noreferrer">@straightupjac</a></code>, inspired by <MuiNextLink href="https://github.com/scaffold-eth/scaffold-eth/tree/buyer-mints-nft" target="_blank">Scaffold-eth</MuiNextLink>
            </p>
          </Stack>
        </p>
        <GetStarted />
        <MintNFT />
      </main>
    </Container>
  )
}
